### ISSUE TITLE
Parameter validation failed. "resourceRequirements", must be one of ...

### ISSUE THREAD

**Issue by 1vash** [brentley/tensorflow-container#1]
I try to reproduce your code but cannot register a task with  **resourceRequirements**
```
            "resourceRequirements": [
                {
                    "type": "GPU",
                    "value": "1"
                }
            ],
```
P.S without **resourceRequirements** lines task can be registered easely. and I also use **us-east-2** region

When I try to register the code with your task definition json file I get the error:
`$ aws ecs register-task-definition --cli-input-json file://gpu-1-taskdef.json
`
> Parameter validation failed:
> Unknown parameter in containerDefinitions[0]: "resourceRequirements", must be one of: name, image, repositoryCredentials, cpu, memory, memoryReservation, links, portMappings, essential, entryPoint, command, environment, mountPoints, volumesFrom, linuxParameters, secrets, hostname, user, workingDirectory, disableNetworking, privileged, readonlyRootFilesystem, dnsServers, dnsSearchDomains, extraHosts, dockerSecurityOptions, interactive, pseudoTerminal, dockerLabels, ulimits, logConfiguration, healthCheck, systemControls

I also tried to move resourceRequirements to other subfields but it didn't help.

From docs I can see that it's valid parameter.
https://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html

Maybe something was changed with **resourceRequirements**? Can you recheck that all works great.

**Comment by brentley** [comment]
What version of the aws-cli do you use? I was on 1.16.98 when I wrote this.
--------
Brent
--------

**Comment by 1vash** [comment]
I used **awscli==1.16.59**  Sorry, I didn't checked aws version. All works fine
Thanks for the help

**Comment by brentley** [comment]
awesome!
